---
version: '3'

services:
  app:
    build: .
    ports:
      - '8000:8000'
  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=climate_db
    volumes:
      - ./db:/var/lib/postgreql/data
